# Generated by Django 5.0.1 on 2026-02-19 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('file', 'File')], max_length=4)),
                ('content', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='drops/')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('filesize', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter ($3/mo)'), ('pro', 'Pro ($8/mo)')], default='free', max_length=16)),
                ('plan_since', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('storage_used_bytes', models.PositiveBigIntegerField(default=0)),
                ('ls_customer_id', models.CharField(blank=True, default='', help_text='Lemon Squeezy customer ID', max_length=64)),
                ('ls_subscription_id', models.CharField(blank=True, default='', help_text='Lemon Squeezy subscription ID', max_length=64)),
                ('ls_subscription_status', models.CharField(blank=True, default='', help_text='active, cancelled, expired, etc.', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
