# Generated by Django 5.0.1 on 2026-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='file',
        ),
        migrations.AddField(
            model_name='drop',
            name='file_public_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='drop',
            name='file_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
