# Generated by Django 5.0.1 on 2026-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('file', 'File')], max_length=4)),
                ('content', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='drops/')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('filesize', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='binfile',
            name='bin',
        ),
        migrations.DeleteModel(
            name='Clipboard',
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
        migrations.DeleteModel(
            name='BinFile',
        ),
    ]
