# Generated by Django 5.0.1 on 2026-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
