# Generated by Django 5.0.1 on 2026-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saveddrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='anon_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
