# Generated by Django 5.0.1 on 2026-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drop_remove_binfile_bin_delete_clipboard_delete_bin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='drp/drops/'),
        ),
    ]
