# Generated by Django 5.0.1 on 2026-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_drop_file_drop_file_public_id_drop_file_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drop',
            unique_together={('ns', 'key')},
        ),
        migrations.AddField(
            model_name='drop',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='max_lifetime_secs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='ns',
            field=models.CharField(choices=[('c', 'Clipboard'), ('f', 'File')], db_index=True, default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='drop',
            name='key',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.RemoveField(
            model_name='drop',
            name='last_accessed',
        ),
    ]
