# Generated by Django 5.0.1 on 2026-02-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drop_last_viewed_at_drop_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='burn',
            field=models.BooleanField(default=False, help_text='Delete after first view'),
        ),
    ]
