# Generated by Django 5.0.1 on 2026-02-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_drop_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='drops/'),
        ),
    ]
