# Generated by Django 5.0.1 on 2026-02-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drop_burn'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='password_hash',
            field=models.CharField(blank=True, default='', help_text='PBKDF2 hash. Empty = no password.', max_length=256),
        ),
    ]
