# Generated by Django 5.0.1 on 2026-02-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drop_expires_at_drop_locked_drop_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ls_customer_id',
            field=models.CharField(blank=True, default='', help_text='Lemon Squeezy customer ID', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_subscription_id',
            field=models.CharField(blank=True, default='', help_text='Lemon Squeezy subscription ID', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_subscription_status',
            field=models.CharField(blank=True, default='', help_text='active, cancelled, expired, etc.', max_length=32),
        ),
    ]
